fs: dlm: remove unused is_granted function
clang with W=1 reports
fs/dlm/lock.c:239:19: error: unused function
  'is_granted' [-Werror,-Wunused-function]
static inline int is_granted(struct dlm_lkb *lkb)
                  ^
This function is not used so remove it.

Signed-off-by: Tom Rix <trix@redhat.com>