maple_tree: remove unused maple_tree functions
clang with W=1 reports
lib/maple_tree.c:331:21: error: unused function
  'mte_set_full' [-Werror,-Wunused-function]
static inline void *mte_set_full(const struct maple_enode *node)
                    ^
lib/maple_tree.c:336:21: error: unused function
  'mte_clear_full' [-Werror,-Wunused-function]
static inline void *mte_clear_full(const struct maple_enode *node)
                    ^
lib/maple_tree.c:341:20: error: unused function
  'mte_has_null' [-Werror,-Wunused-function]
static inline bool mte_has_null(const struct maple_enode *node)
                   ^
These static functions are not used, so remove them.

Signed-off-by: Tom Rix <trix@redhat.com>