bus: fsl-mc: remove unused free_count variable
clang with W=1 reports
drivers/bus/fsl-mc/fsl-mc-allocator.c:560:6: error: variable
  'free_count' set but not used [-Werror,-Wunused-but-set-variable]
        int free_count = 0;
            ^
This variable is not used so remove it.

Signed-off-by: Tom Rix <trix@redhat.com>