fpga: xilinx-pr-decoupler: remove unused xlnx_pr_decouple_read function
clang with W=1 reports
drivers/fpga/xilinx-pr-decoupler.c:37:19: error: unused function 'xlnx_pr_decouple_read' [-Werror,-Wunused-function]
static inline u32 xlnx_pr_decouple_read(const struct xlnx_pr_decoupler_data *d,
                  ^
This static function is not used, so remove it.

Signed-off-by: Tom Rix <trix@redhat.com>