x86/mm/fixmap: rename NR_CPUS to CONFIG_NR_CPUS
Fixes this build error
from arch/x86/xen/platform-pci-unplug.c:11:
...
fixmap.h:103:48: error: ‘NR_CPUS’ undeclared here (not in a function)
  103 |  FIX_KMAP_END = FIX_KMAP_BEGIN + (KM_MAX_IDX * NR_CPUS) - 1,

This block used to be conditional on CONFIG_X86_32 which also
included linux/threads.h which defines NR_CPUS as CONFIG_NR_CPUS.

Since CONFIG_NR_CPUS is already used fixmap.h, instead of including
linux/threads.h again, rename NR_CPUS to CONFIG_NR_CPUS.

Fixes: 14df32670291 ("x86: Support kmap_local() forced debugging")
Signed-off-by: Tom Rix <trix@redhat.com>