ice: change return type of ice_ptp_request_ts() to s8
A gcc 10.3.1 compile error
ice_ptp.h:149:1: error: return type defaults to
  'int' [-Werror=return-type]
  149 | ice_ptp_request_ts(struct ice_ptp_tx *tx, ...
      | ^~~~~~~~~~~~~~~~~~

This stub's return needs to match the decl for
CONFIG_PTP_I588_CLOCK, which matches its use in
ice_txrt.c

Change the implicit int return to s8.

Signed-off-by: Tom Rix <trix@redhat.com>