agp/uninorth: remove unused variable size
For ppc64, gcc with W=1 reports
drivers/char/agp/uninorth-agp.c: In function 'uninorth_create_gatt_table':
drivers/char/agp/uninorth-agp.c:372:13: error: variable
  'size' set but not used [-Werror=unused-but-set-variable]
  372 |         int size;
      |             ^~~~

This variable is not used so remove it.

Signed-off-by: Tom Rix <trix@redhat.com>