power: supply: twl4030-charger: remove unused cur_reg variable
clang with W=1 reports
drivers/power/supply/twl4030_charger.c:242:16: error: variable
  'cur_reg' set but not used [-Werror,-Wunused-but-set-variable]
        unsigned reg, cur_reg;
                      ^
This variable is not used so remove it.

Signed-off-by: Tom Rix <trix@redhat.com>