scsi: lpfc: add depends CPU_FREQ to SCSI_LPFC configury
A compile error

drivers/scsi/lpfc/lpfc_sli.c:7329:26: error: implicit
  declaration of function ‘get_cpu_idle_time’; did you
  mean ‘set_cpu_active’? [-Werror=implicit-function-declaration]
   idle_stat->prev_idle = get_cpu_idle_time(i, &wall, 1);

lpfc_init_idle_stat_hb depends on CPU_FREQ

So add depends CPU_FREQ to the configury.

Signed-off-by: Tom Rix <trix@redhat.com>