comedi: remove unused dma_chain_flag_bits function
clang with W=1 reports
drivers/comedi/drivers/cb_pcidas64.c:377:28: error: unused function
  'dma_chain_flag_bits' [-Werror,-Wunused-function]
static inline unsigned int dma_chain_flag_bits(u16 prepost_bits)
                           ^
This function is not used, so remove it.

Signed-off-by: Tom Rix <trix@redhat.com>