fs/efs: fix variable name when DEBUG is defined
When DEBUG is defined this error occurs

fs/efs/file.c:27:14: error: ‘block’
  undeclared (first use in this function); did you mean ‘iblock’?
    __func__, block, inode->i_blocks, inode->i_size);

From reviewing the if-check, it is clear that iblock is what
is meant. So fix the variable.

Also fix the -Wformat warnings.

Signed-off-by: Tom Rix <trix@redhat.com>