dmaengine: ti: k3-udma: define udma_pm_resume,suspend with CONFIG_PM_SLEEP
gcc reports
drivers/dma/ti/k3-udma.c:5552:12: error: ‘udma_pm_resume’
  defined but not used [-Werror=unused-function]
 5552 | static int udma_pm_resume(struct device *dev)
      |            ^~~~~~~~~~~~~~
drivers/dma/ti/k3-udma.c:5530:12: error: ‘udma_pm_suspend’
  defined but not used [-Werror=unused-function]
 5530 | static int udma_pm_suspend(struct device *dev)
      |            ^~~~~~~~~~~~~~~

These functions are used conditionally with CONFIG_PM_SLEEP,
so they should be likewise defined.

Signed-off-by: Tom Rix <trix@redhat.com>