bpf: BPF_LSM depends on NET
A link error
bpf_lsm.o: in function `bpf_lsm_func_proto':
bpf_lsm.c: undefined reference to `bpf_sk_storage_get_proto'

bpf_sk_storeage building is controlled by BPS_SYSCALL
But it is also in the net subsytem and is controlled by NET.
So add a depends to the BPF_LSM configury.

Signed-off-by: Tom Rix <trix@redhat.com>