bpf: BPF_SYSCALL depends INET
A link error

kernel/bpf/net_namespace.o: In function `bpf_netns_link_release':
net_namespace.c: undefined reference to `bpf_sk_lookup_enabled'

bpf_sk_lookup_enabled is defined with INET
net_namespace is controlled by BPF_SYSCALL

So add a depends on INET to BPF_SYSCALL

Signed-off-by: Tom Rix <trix@redhat.com>