power: supply: core: move psy_has_property()
A ranconfig produces this error
power_supply_core.c:1137:6: error: implicit declaration
  of function 'psy_has_property'
 1137 |  if (psy_has_property(desc, POWER_SUPPLY_PROP_USB_TYPE) &&

psy_has_property() compiling is conditional on THERMAL.  It is used
in __power_supply_register() to check a non thermal property.
So move psy_has_property() out of the THERMAL conditional.

Fixes: 9ba533eb99bb ("power: supply: core: Add psy_has_property()")
Signed-off-by: Tom Rix <trix@redhat.com>