fs/efs: remove unused variable cprt
gcc with W=1 reports
In file included from fs/efs/super.c:18:
fs/efs/efs.h:22:19: error: ‘cprt’ defined but not used [-Werror=unused-const-variable=]
   22 | static const char cprt[] = "EFS: "EFS_VERSION" - (c) 1999 Al Smith <Al.Smith@aeschi.ch.eu.org>";
      |                   ^~~~
This variable is not used so remove it.

Signed-off-by: Tom Rix <trix@redhat.com>