soc: qcom-geni-se: fix configury of qcom-geni-se.c
In a randconfig, qcom-geni-se.c breaks with

drivers/soc/qcom/qcom-geni-se.c: In function ‘geni_remove_earlycon_icc_vote’:
drivers/soc/qcom/qcom-geni-se.c:819:11: error: implicit declaration of function ‘of_get_next_parent’; did you mean ‘of_get_parent’? [-Werror=implicit-function-declaration]
  parent = of_get_next_parent(wrapper->dev->of_node);
           ^~~~~~~~~~~~~~~~~~
           of_get_parent

qcom-geni-sec.c correctly includes the linux/of.h header.
But the header depends on CONFIG_OF being set.

So add depends to QCOM_GENI_SE

Signed-off-by: Tom Rix <trix@redhat.com>