Revert "scsi: hisi_sas: Fix some issues related to asd_sas_port->phy_list"
This reverts commit 29e2bac87421c613782ccb510c76c5efbecac0cf.

drivers/scsi/hisi_sas/hisi_sas_main.c:1536:21: error: variable 'sas_phy' is uninitialized when used here [-Werror,-Wuninitialized]
                if (!(state & BIT(sas_phy->id)))