net: dsa: select OF_MDIO for NET_DSA_QCA8K
The build is failing with this error
qca8k.c: In function ‘qca8k_mdio_register’:
qca8k.c:797:9: error: implicit declaration of
  function ‘devm_of_mdiobus_register’

devm_of_mdiobus_register() is conditionally declared in
include/linux/of_mdio.h  The condition is CONFIG_OF_MDIO.

So add 'select CONFIG_OF_MDIO' to the qca8k.c configury.

Signed-off-by: Tom Rix <trix@redhat.com>