drm/nouveau/acr: remove unused variable loc
gcc with W=1 reports
drivers/gpu/drm/nouveau/nvkm/subdev/acr/lsfw.c:221:21: error: variable
  ‘loc’ set but not used [-Werror=unused-but-set-variable]
  221 |                 u32 loc, sig, cnt, *meta;
      |                     ^~~
This variable is not used so remove it.

Signed-off-by: Tom Rix <trix@redhat.com>