init: Define rotate conditionally on ! CONFIG_390
For s390, gcc with W=1 reports
init/do_mounts_rd.c:192:24: error: variable
  'rotate' set but not used [-Werror=unused-but-set-variable]
  192 |         unsigned short rotate = 0;
      |                        ^~~~~~

rotate is not used for s390 so should be conditionally defined.

Signed-off-by: Tom Rix <trix@redhat.com>