tty: define hung_up_tty_compat_ioctl with CONFIG_COMPAT
gcc reports
drivers/tty/tty_io.c:446:13: error: ‘hung_up_tty_compat_ioctl’
  defined but not used [-Werror=unused-function]
  446 | static long hung_up_tty_compat_ioctl(struct file *file,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~

hung_up_tty_compat_ioctl is used conditionally with CONFIG_COMPAT,
so it should be likewise defined.

Signed-off-by: Tom Rix <trix@redhat.com>