remove undefined variable when DEBUG is defined
When DEBUG is defined this error occurs

drivers/scsi/aha1740.c:342:26: error: ‘bufflen’
  undeclared (first use in this function)
         target, *cmd, i, bufflen);
                          ^~~~~~~