net: cdc_ncm: USB_NET_CDC_NCM selects USB_NET_CDCETHER
A link error

ld: drivers/net/usb/cdc_ncm.o:
  undefined reference to `usbnet_cdc_update_filter'

usbnet_cdc_update_filter is defined in cdc_ether.c
Building of cdc_ether.o is controlled by USB_NET_CDCETHER

Building of cdc_ncm.o is controlled by USB_NET_CDC_NCM

So add a select USB_NET_CDCETHER to USB_NET_CDC_NCM

Signed-off-by: Tom Rix <trix@redhat.com>