fs: dlm: remove unused count_match variable
clang with W=1 reports
fs/dlm/dir.c:67:26: error: variable
  'count_match' set but not used [-Werror,-Wunused-but-set-variable]
        unsigned int count = 0, count_match = 0, count_bad = 0, count_add = 0;
                                ^
This variable is not used so remove it.

Signed-off-by: Tom Rix <trix@redhat.com>