fs: vboxsf: remove unused out_len variable
clang with W=1 reports
fs/vboxsf/utils.c:442:9: error: variable
  'out_len' set but not used [-Werror,-Wunused-but-set-variable]
        size_t out_len;
               ^
This variable is not used so remove it.

Signed-off-by: Tom Rix <trix@redhat.com>