thermal/drivers/tsens: remove unused variable ops_v0_1
gcc with W=1 reports
drivers/thermal/qcom/tsens-v0_1.c:328:31: error:
  ‘ops_v0_1’ defined but not used [-Werror=unused-const-variable=]
  328 | static const struct tsens_ops ops_v0_1 = {
      |                               ^~~~~~~~

This variable is not used, so remove it.

Signed-off-by: Tom Rix <trix@redhat.com>