[media] mb86a20s: remove unused active_layers variable
clang with W=1 reports
drivers/media/dvb-frontends/mb86a20s.c:1572:6: error: variable
  'active_layers' set but not used [-Werror,-Wunused-but-set-variable]
        int active_layers = 0, pre_ber_layers = 0, post_ber_layers = 0;
            ^
This variable is not used so remove it.

Signed-off-by: Tom Rix <trix@redhat.com>